spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_gobang?characterEncoding=utf8&useSSL=false
    username: root
    password: 3345576297ltLT
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev

  # 设置 MyBatis 的 xml 保存路径
  mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true

  logging:
    file:
      name: logs/springboot.log
    logback:
      rollingpolicy:
        max-file-size: 10MB
        file-name-pattern: logs/springboot.log.%d{yyyy-MM-dd}.%i
    level:
      com:
        example:
          demo: debug
